### ISSUE TITLE
Dots are significant in hotmail accounts

### ISSUE THREAD

**Issue by dandv** [johno/normalize-email#1]
I've just created dan.dascal2@hotmail.com and could send email to it. Sending email to dandascal2@hotmail.com failed:

![image](https://cloud.githubusercontent.com/assets/33569/8764843/925a3dee-2da5-11e5-8bed-a0c1542b5752.png)

Same for outlook.com. Haven't tried live.com.

**Comment by johno** [comment]
Thanks for taking the time to create, and verify this issue. I appreciate it! From what I can tell it _might_ just be gmail accounts that have insignificant dots?

I'm assuming by #2 you may have a fix?

**Comment by dandv** [comment]
Hi John,

In the meantime I ended up rewriting the algo so much that it no longer makes sense to submit a fork. I'll publish a package this week under [iDoRecall](https://github.com/idorecall).

**Comment by dandv** [comment]
Here's the new approach - https://github.com/iDoRecall/email-normalize

It supports a wider range of domains (Yahoo! in any country, Microsoft, FastMail), plus any Google Apps for Work domain.

Right now it's a Meteor.js package because that's our use case, but it should be fairly easy to factor out the common Node.js code. PRs welcome.

**Comment by Kongpcmail** [comment]
> I've just created [dan.dascal2@hotmail.com](mailto:dan.dascal2@hotmail.com) and could send email to it. Sending email to [dandascal2@hotmail.com](mailto:dandascal2@hotmail.com) failed:
> 
> ![image](https://cloud.githubusercontent.com/assets/33569/8764843/925a3dee-2da5-11e5-8bed-a0c1542b5752.png)
> 
> Same for outlook.com. Haven't tried live.com.

@kongpcmail
