### ISSUE TITLE
Will you accept PRs that use semicolons?

### ISSUE THREAD

**Issue by dandv** [johno/normalize-email#2]
I have a PR ready that adds Yahoo support, but I've had [trouble in the past with code without semicolons](https://github.com/Zolmeister/promiz/issues/8). How keen are you on keeping the style and relying on ASI?

**Comment by johno** [comment]
Sure. I have a preference for Standard Style, but I'd much rather have a contribution for Yahoo support. So, feel free to submit a PR adding semicolons. : )
